meta:
  environment: (( param "please set meta environment" ))
  dns_root: (( param "please set meta dns_root" ))
  security_groups: (( param "please set meta security_groups" ))

  stemcell:
    name: bosh-aws-xen-hvm-ubuntu-trusty-go_agent
    version: latest

jobs:
  - name: vault
    networks:
      - name: safe

compilation:
  cloud_properties:
    instance_type: m3.medium

resource_pools:
  - name: small
    cloud_properties:
      instance_type: m3.medium

networks:
  - name: floating
    type: vip
    cloud_properties: {}
  - name: safe
    type: dynamic
    cloud_properties:
      security_groups: (( grab meta.security_groups ))
